### PR TITLE
Fix outdated import path to AggregatorV3Interface.sol

### PR DESCRIPTION
**Pull request by 0xValerio**
The import path of AggregatorV3Interface.sol was outdated in FundMe.sol

updated to new path in Chainlink's Repo ->
"@chainlink/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol"

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Thank you!

**Comment by spencerj411** [comment]
Hi! Could I get a confirmation on this?

I ran `forge install smartcontractkit/chainlink-brownie-contracts@0.6.1 --no-commit` and the `chainlink-brownie-contracts` library doesn't have a folder called `/shared/`. @valeriofichera Could I ask you the command you ran to install chainlink?

**Comment by lampochka-ds** [comment]
> Hi! Could I get a confirmation on this?
> 
> I ran `forge install smartcontractkit/chainlink-brownie-contracts@0.6.1 --no-commit` and the `chainlink-brownie-contracts` library doesn't have a folder called `/shared/`. @valeriofichera Could I ask you the command you ran to install chainlink?

q, just delete `/shared` from path in `FundMe.sol`

**Comment by 0xValerio** [comment]
GM,

sorry for the late reply.

Here the full path to AggregatorV3Interface.sol, as its working for me: 
https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol

Here you can see, the official AggregatorV3Interface.sol has been moved to the /shared/ folder. Also I have not been using the /chainlink-brownie-contracts/ but the official /chainlink/ library. You are right, the paths are different, yet leading both to the same AggregatorV3Interface.sol.

This is not working for you, since you are not using the official repo, where there is no /shared/ folder. Therefore in regards to your question: Yes, when using the outdated non-official /chainlink-brownie-contracts/ library you could just delete /shared from the path in FundMe.sol from the tutorial and it should work.

All in all, both paths will work and I would suggest to stick with the official path going forward, unless it would cause to much complications, as it will probably be better maintained over time and lead to less confusion in the future. However, both will work and if you want to stick with the /chainlink-brownie-contracts/ we can leave it as before.

Here again for comparison:

Official path:
https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol

non-official path:
https://github.com/smartcontractkit/chainlink-brownie-contracts/blob/main/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol

Alternatively, the /chainlink-brownie-contracts/ could be updated to match the official path.

Thanks @lampochka-ds @spencerj411 for pointing this out :)

**Comment by lampochka-ds** [comment]
> All in all, both paths will work and I would suggest to stick with the official path going forward, unless it would cause to much complications, as it will probably be better maintained over time and lead to less confusion in the future. However, both will work and if you want to stick with the /chainlink-brownie-contracts/ we can leave it as before.

Yp, thx for answer!
I mean that in course it was used brownie-contracts, so mb it will be easier to keep track on it. 
But it seems like both approaches work. Great, gl in your way!

**Pull request merged**
