### PR TITLE
Changed the Imported Path

### PR DESCRIPTION
**Pull request by MostPow3rful**
Removed /shared/

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Why? I think shared is correct now.

**Comment by MostPow3rful** [comment]
i removed /shared/ and worked succesfully. IDK

**Comment by PatrickAlphaC** [comment]
Quite odd... Removing shared did _not_ work for me... hmm.... remix doing some odd stuff it seems

**Comment by VasilGrozdanov** [comment]
I removed it too, because the installed lib follows the path
```
contracts/src/v0.8/interfaces/AggregatorV3Interface.sol
```
if there's shared as well in the path, then it's incorrect and I get an error on compilation
```Solidity
TypeError: Invalid type for argument in function call. Invalid implicit conversion from contract AggregatorV3Interface to contract AggregatorV3Interface requested.
  --> contracts/FundMe.sol:27:45:
   |
27 |         require(msg.value.getConversionRate(s_priceFeed) >= MINIMUM_USD, "You need to spend more ETH!");
   |                                             ^^^^^^^^^^^

AggregatorV3Interface private s_priceFeed
```
According to chat gpt, because the import paths are different, Solidity thinks these two AggregatorV3Interfaces in FundMe.sol and PriceConverter.sol are different.

**Pull request closed without merging**
